version: "3"

services:

  event-extraction:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: eventhub-extraction
    volumes:
      - .:/app
    env_file:
      - .env
    restart: on-failure