name: Push docker image to ACR

# Deploy when change is made to main branch
on:
  push:
    branches:
      - main

# Jobs to execute
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      GMAIL_USER_EMAIL: ${{ secrets.GMAIL_USER_EMAIL }}
      MS_BLOB_CONNECTION_STRING: ${{ secrets.MS_BLOB_CONNECTION_STRING }}
      MS_BLOB_CONTAINER_NAME: ${{ secrets.MS_BLOB_CONTAINER_NAME }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
    steps:

      # Download source code into GitHub Actions runner (ubuntu-latest VM)
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Login via Azure CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: 'Log into ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        
      - name: "Build and push Docker image to ACR"
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/webscraper:${{ github.sha }} \
            --build-arg GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD \
            --build-arg GMAIL_PASSWORD=$GMAIL_PASSWORD \
            --build-arg GMAIL_USER_EMAIL=$GMAIL_USER_EMAIL \
            --build-arg MS_BLOB_CONNECTION_STRING=$MS_BLOB_CONNECTION_STRING \
            --build-arg MS_BLOB_CONTAINER_NAME=$MS_BLOB_CONTAINER_NAME \
            --build-arg OPENAI_KEY=$OPENAI_KEY
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/webscraper:${{ github.sha }}