name: Push docker image to ACR

# Deploy when change is made to main branch
on:
  push:
    branches:
      - main

# Jobs to execute
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      # Download source code into GitHub Actions runner (ubuntu-latest VM)
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Login via Azure CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: 'Log into ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        
      - name: "Build and push Docker image to ACR"
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/webscraper:latest \
            --build-arg GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }} \
            --build-arg GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }} \
            --build-arg GMAIL_USER_EMAIL=${{ secrets.GMAIL_USER_EMAIL }} \
            --build-arg MS_BLOB_CONNECTION_STRING=${{ secrets.MS_BLOB_CONNECTION_STRING }} \
            --build-arg MS_BLOB_CONTAINER_NAME=${{ secrets.MS_BLOB_CONTAINER_NAME }} \
            --build-arg OPENAI_KEY=${{ secrets.OPENAI_KEY }} \
            --build-arg YOUTUBE_DATA_API_KEY=${{ secrets.YOUTUBE_DATA_API_KEY }} \
            --build-arg SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }} \
            --build-arg SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/webscraper:latest

      # Update Azure Container Apps Job to use the new image only
      - name: "Deploy to Azure Container Apps"
        run: |
          az containerapp job update \
            --name webscraper-running-container-ae \
            --resource-group Event-Hub-Extractor \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/webscraper:latest